# Generated by Django 2.2 on 2019-06-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deptid', models.CharField(max_length=16)),
                ('deptname', models.CharField(max_length=64)),
                ('upperdeptid', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.CharField(max_length=16)),
                ('empname', models.CharField(max_length=64)),
                ('deptid', models.CharField(max_length=16)),
                ('mailaddress', models.CharField(max_length=128)),
            ],
        ),
    ]
