# Generated by Django 2.2 on 2019-06-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_testmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='AssetId',
            field=models.CharField(default='DCC/0000000000', editable=False, max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
